# Generated by Django 4.1.2 on 2022-10-30 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(default=uuid.UUID('bd40401a-07e8-418a-ba4c-a9d3ee003365'), primary_key=True, serialize=False, unique=True)),
                ('group_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('group_members', models.IntegerField(default=0)),
                ('group_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('groupId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('can_upload_answer', models.BooleanField(default=True, editable=False)),
                ('groupname', models.ManyToManyField(to='group.group')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
