# Generated by Django 4.1.2 on 2022-11-13 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStudentsRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('groupname', models.CharField(max_length=100)),
                ('groupid', models.UUIDField()),
                ('studentid', models.IntegerField()),
                ('studentemail', models.EmailField(max_length=254)),
                ('joiningtime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('groupid', models.UUIDField(default=uuid.UUID('df208caa-4bdb-477d-8c70-0b3ac4df1da8'))),
                ('group_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('group_members', models.IntegerField(default=0)),
                ('group_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
