# Generated by Django 4.1.2 on 2022-11-10 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupid',
            field=models.UUIDField(default=uuid.UUID('4d23ce13-0ff4-46da-b4e7-60d002517ca7')),
        ),
    ]
