# Generated by Django 4.1.2 on 2022-10-31 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.IntegerField(default=uuid.UUID('aab0aeee-f9c7-4a96-8cdb-7d8e9ac52f51'), primary_key=True, serialize=False, unique=True),
        ),
    ]
