# Generated by Django 4.1.2 on 2022-11-10 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupid',
            field=models.UUIDField(default=uuid.UUID('919b1287-59b3-4db4-8e18-597382bf0edf')),
        ),
    ]
