# Generated by Django 4.1.2 on 2022-10-31 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='groupid',
            field=models.UUIDField(default=uuid.UUID('170172d2-8e16-4a15-80c5-f351232f80c5')),
        ),
    ]
