# Generated by Django 4.1.2 on 2022-11-10 16:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_group_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupid',
            field=models.UUIDField(default=uuid.UUID('45bf987b-a8c3-4feb-8b6d-502ee1340aad')),
        ),
    ]
