# Generated by Django 4.1.2 on 2022-11-01 17:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_group_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupid',
            field=models.UUIDField(default=uuid.UUID('c7e160ad-71b5-45db-aceb-0d87040f23b9')),
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
    ]
