# Generated by Django 4.1.2 on 2022-10-31 18:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_group_groupid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='groupId',
            new_name='joinId',
        ),
        migrations.AlterField(
            model_name='group',
            name='groupid',
            field=models.UUIDField(default=uuid.UUID('52eec95d-563f-4510-b364-137e37b0735e')),
        ),
    ]
