# Generated by Django 4.1.2 on 2022-11-01 17:43

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_group_groupid_delete_groupmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStudentsRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('groupname', models.CharField(max_length=100)),
                ('groupid', models.URLField()),
                ('studentid', models.IntegerField()),
                ('studentemail', models.EmailField(max_length=254)),
                ('joiningtime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='groupid',
            field=models.UUIDField(default=uuid.UUID('25dc9b8a-37b6-42d3-8333-555ba1b9a096')),
        ),
    ]
