# Generated by Django 4.1.2 on 2022-11-01 17:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_groupstudentsrecord_alter_group_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupid',
            field=models.UUIDField(default=uuid.UUID('5eea94b1-941f-4050-a2bd-0375a0f5ff3b')),
        ),
    ]
