# Generated by Django 4.1.2 on 2022-11-02 17:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_group_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupid',
            field=models.UUIDField(default=uuid.UUID('1548b46d-1430-4b90-93ae-4a67e03457ec')),
        ),
    ]
