# Generated by Django 4.1.2 on 2022-11-02 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_alter_group_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupid',
            field=models.UUIDField(default=uuid.UUID('44a1cc98-67a0-4635-81b9-8c4e859f97a0')),
        ),
    ]
