# Generated by Django 4.1.2 on 2022-11-05 19:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_alter_group_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupid',
            field=models.UUIDField(default=uuid.UUID('49e1dbf3-a942-4bfd-8b9c-0ed7c085bd83')),
        ),
    ]
