# Generated by Django 4.1.2 on 2022-10-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='answer_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='assignment_upload',
            field=models.BooleanField(default=False),
        ),
    ]
