# Generated by Django 4.1.2 on 2022-10-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_firstname_alter_user_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stream',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
