# Generated by Django 4.1.2 on 2022-10-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_firstname_alter_user_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
