# Generated by Django 4.1.2 on 2022-11-05 19:05

import assignment.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignmentID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('assignmentName', models.CharField(blank=True, max_length=200)),
                ('assignmentFile', models.FileField(upload_to=assignment.models.user_directory_path)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('groupID', models.UUIDField(blank=True)),
                ('submissionTime', models.DateTimeField(blank=True)),
            ],
        ),
    ]
